---
- name: Create etcd service
  docker_swarm_service:
    name: etcd
    image: docker.io/bitnami/etcd:latest
    command: 'etcd -listen-peer-urls=http://10.170.0.5:2380 -advertise-client-urls=http://10.170.0.5:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://10.170.0.5:2380 --listen-metrics-urls=http://10.170.0.5:2381 --initial-cluster default=http://10.170.0.5:2380'
    reservations:
      cpus: 0.25
      memory: 20M
    limits:
      cpus: 0.50
      memory: 50M
      healthcheck:
        test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:2381/health"]
        interval: 30s
        timeout: 20s
        retries: 3
      ports:
        - 2379:2379
      network_mode: overlay