---
- hosts: all

- become: yes
  become_user: "{{ lookup('env','jayhwa_lor') }}"
  tasks:

  # Create milvus-etcd
  # --
  # 
  - name: Create milvus-etcd
    community.docker.docker_container:
      name: milvus-etcd
      image: "quay.io/coreos/etcd:latest"
      # command: etcd -listen-peer-urls=http://10.170.0.4:2380 -advertise-client-urls=http://10.170.0.4:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://10.170.0.4:2380 --listen-metrics-urls=http://10.170.0.4:2381 --initial-cluster default=http://10.170.0.4:2380
      # healthcheck:
      #   test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:2381/health"]
      #   interval: 30s
      #   timeout: 20s
      #   retries: 3
      # network_mode: host
      ports:
        - "2379:2379"
      restart_policy: always

  # Create milvus-minio
  # --
  # 
  # - name: Create milvus-minio
  #   hosts: 34.92.97.227
  #   community.docker.docker_container:
  #     name: milvus-minio
  #     image: "docker.io/portainer/portainer-ce"
  #     network_mode: host
  #     ports:
  #       - "9443:9443"
  #     restart_policy: always

  # Create milvus-pulsar
  # --
  # 
  # - name: Create milvus-pulsar
  #   hosts: 34.92.97.227
  #   community.docker.docker_container:
  #     name: milvus-pulsar
  #     image: "docker.io/portainer/portainer-ce"
  #     network_mode: host
  #     ports:
  #       - "9443:9443"
  #     restart_policy: always

  # Create milvus-querynode
  # --
  # 
#   - name: Create milvus-querynode
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-querynode
#       image: "docker.io/portainer/portainer-ce"
#       ports:
#         - "9443:9443"
#       restart_policy: always

#   # Deploy milvus-querycoord
#   # --
#   #   
#   - name: Deploy milvus-querycoord
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-querycoord
#       image: "docker.io/portainer/portainer-ce"
#       ports:
#         - "9443:9443"
#       restart_policy: always

# - hosts: 10.170.0.5
# - become: yes
#   become_user: "{{ lookup('env','jayhwa_lor') }}"
#   tasks:

#   # Deploy milvus-rootcoord
#   # --
#   #   
#   - name: Deploy milvus-rootcoord
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-rootcoord
#       image: "docker.io/portainer/portainer-ce"
#       ports:
#         - "9443:9443"
#       restart_policy: always

#   # Deploy milvus-proxy
#   # --
#   #   
#   - name: Deploy milvus-proxy
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-proxy
#       image: "docker.io/portainer/portainer-ce"
#       network_mode: host
#       ports:
#         - "9443:9443"
#       restart_policy: always

#   # Deploy milvus-indexcoord
#   # --
#   #   
#   - name: Deploy milvus-indexcoord
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-indexcoord
#       image: "docker.io/portainer/portainer-ce"
#       ports:
#         - "9443:9443"
#       restart_policy: always
  
#   # Deploy milvus-indexnode
#   # --
#   #   
#   - name: Deploy milvus-indexnode
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-indexnode
#       image: "docker.io/portainer/portainer-ce"
#       ports:
#         - "9443:9443"
#       restart_policy: always
  
#   # Deploy milvus-datacoord
#   # --
#   #   
#   - name: Deploy milvus-datacoord
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-datacoord
#       image: "docker.io/portainer/portainer-ce"
#       ports:
#         - "9443:9443"
#       restart_policy: always
  
#   # Deploy milvus-datanode
#   # --
#   #   
#   - name: Deploy milvus-datanode
#     hosts: 34.92.97.227
#     community.docker.docker_container:
#       name: milvus-datanode
#       image: "docker.io/portainer/portainer-ce"
#       ports:
#         - "9443:9443"
#       restart_policy: always
