---
  # # Create milvus-etcd
  # - name: Create milvus-etcd
  #   hosts:  swarm-manager
  #   # become: yes
  #   # become_user: root
  #   roles:
  #     - deploy-etcd

- name: Create milvus-etcd, minio, pulsar
  hosts: swarm-manager
  become: yes
  become_user: root
  vars:
    network: milvus_net
  tags: docker
  tasks:
  - name: Create milvus-etcd
    docker_container: 
      name: milvus-etcd
      image: quay.io/coreos/etcd:latest
      command: "etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --listen-metrics-urls=http://127.0.0.1:2381 --initial-cluster default=http://127.0.0.1:2380"
      healthcheck:
        test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://127.0.0.1:2381/health"]
        interval: 30s
        timeout: 20s
        retries: 3
      ports:
        - 2379
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.8"

  - name: milvus-minio
    docker_container: 
      name: milvus-minio
      image: minio/minio:RELEASE.2020-12-03T00-03-10Z
      env:
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
      command: "minio server /minio_data"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.10"
      ports:
        - 9000

  - name: milvus-pulsar
    docker_container: 
      name: milvus-pulsar
      image: apachepulsar/pulsar:latest
      command: "bin/pulsar standalone"
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.11"
      ports:
        - "6650"

  - name: milvus-proxy
    docker_container: 
      name: milvus-proxy
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: "milvus run proxy"
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650"
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.35"
      ports:
        - "19530"
        - "9091"

  - name: milvus-querycoord
    docker_container: 
      name: milvus-querycoord
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: "milvus run querycoord"
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650"
        ROOT_COORD_ADDRESS: "10.0.2.29:53100"
        DATA_COORD_ADDRESS: "10.0.2.28:13333"
        INDEX_COORD_ADDRESS: "10.0.2.30:31000"
        QUERY_COORD_ADDRESS: "10.0.2.31:19531"
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.31"
      ports:
        - "19531"
        - "9091"  

- name: Create all kinds of milvus coord & node
  hosts: swarm-worker-01
  become: yes
  become_user: root
  vars:
    network: milvus_net
    # etcd: "{{ hostvars['swarm-manager']['etcd']['container']['NetworkSettings']['Networks']['milvus_net']['IPAddress'] }}:2379"
  tags: docker
  tasks:
  - name: milvus-datacoord
    docker_container: 
      name: milvus-datacoord
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: ["milvus", "run", "datacoord"]
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650"
        ROOT_COORD_ADDRESS: "10.0.2.29:53100"
        DATA_COORD_ADDRESS: "10.0.2.28:13333"
        INDEX_COORD_ADDRESS: "10.0.2.30:31000"
        QUERY_COORD_ADDRESS: "10.0.2.31:19531"
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.28"
      ports:
        - "13333"
        - "9091"   
 
  - name: milvus-rootcoord
    docker_container: 
      name: milvus-rootcoord
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: ["milvus", "run", "rootcoord"]
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650"
        ROOT_COORD_ADDRESS: "10.0.2.29:53100"
        DATA_COORD_ADDRESS: "10.0.2.28:13333"
        INDEX_COORD_ADDRESS: "10.0.2.30:31000"
        QUERY_COORD_ADDRESS: "10.0.2.31:19531"
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.29"
      ports:
        - "53100"
        - "9091"
    
  - name: milvus-indexcoord
    docker_container: 
      name: milvus-indexcoord
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: ["milvus", "run", "indexcoord"]
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650"
        ROOT_COORD_ADDRESS: "10.0.2.29:53100"
        DATA_COORD_ADDRESS: "10.0.2.28:13333"
        INDEX_COORD_ADDRESS: "10.0.2.30:31000"
        QUERY_COORD_ADDRESS: "10.0.2.31:19531"
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.30"
      ports:
        - "31000"
        - "9091"  
    
  - name: milvus-querynode
    docker_container: 
      name: milvus-querynode
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: "milvus run querynode"
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650"
        QUERY_COORD_ADDRESS: "10.0.2.31:19531"         
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.32"
      ports:
        - "21123"
        - "9091"

  - name: milvus-datanode
    docker_container: 
      name: milvus-datanode
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: "milvus run datanode"
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650" 
        DATA_COORD_ADDRESS: "10.0.2.28:13333"       
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.33"
      ports:
        - "21124"
        - "9091"

  - name: milvus-indexnode
    docker_container: 
      name: milvus-indexnode
      image: milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1
      command: "milvus run indexnode"
      env:
        ETCD_ENDPOINTS: "10.0.2.8:2379"
        MINIO_ADDRESS: "10.0.2.10:9000"
        PULSAR_ADDRESS: "pulsar://10.0.2.11:6650"
        INDEX_COORD_ADDRESS: "10.0.2.30:31000"
      network_mode: "{{ network }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "10.0.2.34"
      ports:
        - "21121"
        - "9091"
