---
- name: Create milvus-index/data nodes coords, proxy
  hosts: swarm-manager
  become: yes
  become_user: root
  tags: docker
  tasks:
  - name: "{{pre}}datacoord"
    docker_container:
      name: "{{pre}}datacoord"
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "datacoord"]
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        DATA_COORD_ADDRESS: "{{DATA_COORD_ADDRESS}}"
        METRICS_PORT: "9091"
      network_mode: "{{network}}"

  - name: "{{pre}}indexcoord"
    docker_container:
      name: "{{pre}}indexcoord"
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "indexcoord"]
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        METRICS_PORT: "9092"        
        INDEX_COORD_ADDRESS: "{{INDEX_COORD_ADDRESS}}"
      network_mode: "{{network}}"

  - name: "{{pre}}datanode"
    docker_container:
      name: "{{pre}}datanode"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run datanode"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        METRICS_PORT: "9093"
      network_mode: "{{network}}"

  - name: "{{pre}}indexnode"
    docker_container:
      name: "{{pre}}indexnode"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run indexnode"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        INDEX_COORD_ADDRESS: "{{INDEX_COORD_ADDRESS}}"
        METRICS_PORT: "9094"
      network_mode: "{{network}}"

  - name: "{{pre}}proxy"
    docker_container:
      name: "{{pre}}proxy"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run proxy"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        METRICS_PORT: "9095"
      network_mode: "{{network}}"

- name: Create milvus-index/data nodes coords, proxy
  hosts: swarm-worker-01
  become: yes
  become_user: root
  tags: docker
  tasks:
  - name: "{{pre}}rootcoord"
    docker_container:
      name: "{{pre}}rootcoord"
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "rootcoord"]
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        QUERY_COORD_ADDRESS: "{{QUERY_COORD_ADDRESS}}"
        METRICS_PORT: "9091"
      network_mode: "{{ network }}"

  - name: "{{pre}}querycoord"
    docker_container:
      name: "{{pre}}querycoord"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run querycoord"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        QUERY_COORD_ADDRESS: "{{QUERY_COORD_ADDRESS}}"
        METRICS_PORT: "9092"
      network_mode: "{{ network }}"

  - name: "{{pre}}querynode"
    docker_container:
      name: "{{pre}}querynode"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run querynode"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        METRICS_PORT: "9093"
      network_mode: "{{ network }}"
