---
- name: Create Nodes
  hosts: swarm-manager
  become: yes
  become_user: root
  tags: docker
  tasks:
  - name: "{{pre}}indexnode"
    docker_container:
      name: "{{pre}}indexnode"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run indexnode"
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
        INDEX_COORD_ADDRESS: "{{INDEX_COORD_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "21121:21121"
        - 4000-65535
        - "9091"

  - name: "{{pre}}datanode"
    docker_container:
      name: "{{pre}}datanode"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run datanode"
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "21124:21124"
        - 4000-65535
        - "9091"

  - name: "{{pre}}proxy"
    docker_container:
      name: "{{pre}}proxy"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run proxy"
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "19530:19530"
        - 4000-65535
        - "9091"

- name: Create Coords
  hosts: swarm-worker-01
  become: yes
  become_user: root
  tags: docker
  tasks:
  - name: "{{pre}}querynode01"
    docker_container:
      name: "{{pre}}querynode01"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run querynode"
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "21123"
        - 4000-65535
        - "9091"

  - name: "{{pre}}querynode02"
    docker_container:
      name: "{{pre}}querynode02"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run querynode"
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "21123"
        - 4000-65535
        - "9091"

  - name: "{{pre}}indexcoord"
    docker_container:
      name: "{{pre}}indexcoord"
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "indexcoord"]
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
        INDEX_COORD_ADDRESS: "{{INDEX_COORD_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "31000:31000"
        - 4000-65535
        - "9091"

  - name: "{{pre}}querycoord"
    docker_container:
      name: "{{pre}}querycoord"
      image: milvusdb/milvus:v2.0.1
      command: "milvus run querycoord"
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
        QUERY_COORD_ADDRESS: "{{QUERY_COORD_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "19531:19531"
        - 4000-65535
        - "9091"

  - name: "{{pre}}datacoord"
    docker_container:
      name: "{{pre}}datacoord"
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "datacoord"]
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
        DATA_COORD_ADDRESS: "{{DATA_COORD_ADDRESS}}"
      network_mode: "{{ network }}"
      ports:
        # - "13333:13333"
        - 4000-65535
        - "9091"

  - name: "{{pre}}rootcoord"
    docker_container:
      name: "{{pre}}rootcoord"
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "rootcoord"]
      env:
        ETCD_ENDPOINTS: "{{ETCD_ENDPOINTS}}"
        MINIO_ADDRESS: "{{MINIO_ADDRESS}}"
        PULSAR_ADDRESS: "{{PULSAR_ADDRESS}}"
        QUERY_COORD_ADDRESS: 10.170.0.8:19531
      network_mode: "{{ network }}"
      ports:
        # - "53100:53100"
        - 4000-65535
        - "9091"