---
- name: Create milvus-etcd, minio, pulsar, network
  hosts: swarm-worker-01
  become: yes
  become_user: root
  tags: docker
  tasks:
  - name: etcd
    docker_container: 
      name: etcd
      image: quay.io/coreos/etcd:v3.5.0
      command: etcd -listen-peer-urls=http://10.170.0.8:2380 -advertise-client-urls=http://10.170.0.8:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://10.170.0.8:2380 --listen-metrics-urls=http://10.170.0.8:2381 --initial-cluster default=http://10.170.0.8:2380
      healthcheck:
        test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://10.170.0.8:2381/health"]
        interval: 30s
        timeout: 20s
        retries: 3
      env:
        ETCD_AUTO_COMPACTION_MODE: revision
        ETCD_AUTO_COMPACTION_RETENTION: "1000"
        ETCD_QUOTA_BACKEND_BYTES: "4294967296"
      network_mode: bridge
      ports:
        - 2379:2379

  - name: "pulsar"
    docker_container:
      name: pulsar
      image: apachepulsar/pulsar:2.8.2
      env:
        # bin/apply-config-from-env.py script will modify the configuration file based on the environment variables
        # nettyMaxFrameSizeBytes must be calculated from maxMessageSize + 10240 (padding)
        nettyMaxFrameSizeBytes: "104867840" # this is 104857600 + 10240 (padding)
        defaultRetentionTimeInMinutes: "10080"
        defaultRetentionSizeInMB: "8192"
        # maxMessageSize is missing from standalone.conf, must use PULSAR_PREFIX_ to get it configured
        PULSAR_PREFIX_maxMessageSize: "104857600"
        PULSAR_GC: -XX:+UseG1GC
      command: "bin/pulsar standalone --no-functions-worker --no-stream-storage" #/bin/bash -c bin/apply-config-from-env.py conf/standalone.conf &&
      network_mode: bridge

  - name: "minio"
    docker_container:
      name: minio
      image: minio/minio:RELEASE.2022-03-17T06-34-49Z
      env:
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
      command: "minio server /minio_data"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      network_mode: bridge

  - name: "querycoord"
    docker_container:
      name: bridge_querycoord
      image: milvusdb/milvus:v2.0.1
      command: "milvus run querycoord"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        QUERY_COORD_ADDRESS: "bridge_querycoord::19531"
      network_mode: bridge
      ports:
        - "19531"
        - "9091"  

  - name: "querynode"
    docker_container:
      name: bridge_querynode
      image: milvusdb/milvus:v2.0.1
      command: "milvus run querynode"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
      network_mode: bridge
      ports:
        - "21123"
        - "9091"  

  - name: "rootcoord"
    docker_container: 
      name: bridge_rootcoord
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "rootcoord"]
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        QUERY_COORD_ADDRESS: "bridge_querycoord:19531"
      network_mode: bridge
      ports:
        - "53100"
        - "9091"

  - name: datacoord
    docker_container: 
      name: bridge_datacoord
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "datacoord"]
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        DATA_COORD_ADDRESS: "bridge_datacoord:13333"
      network_mode: bridge
      ports:
        - "13333"
        - "9091"   

  - name: indexcoord
    docker_container: 
      name: bridge_indexcoord
      image: milvusdb/milvus:v2.0.1
      command: ["milvus", "run", "indexcoord"]
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        INDEX_COORD_ADDRESS: "bridge_indexcoord:31000"
      network_mode: bridge
      ports:
        - "31000"
        - "9091"  

  - name: datanode
    docker_container: 
      name: bridge_datanode
      image: milvusdb/milvus:v2.0.1
      command: "milvus run datanode"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
      network_mode: bridge
      ports:
        - "21124"
        - "9091"

  - name: "indexnode"
    docker_container: 
      name: bridge_indexnode
      image: milvusdb/milvus:v2.0.1
      command: "milvus run indexnode"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
        INDEX_COORD_ADDRESS: "bridge_indexcoord:31000"
      network_mode: bridge
      ports:
        - "21121"
        - "9091"

  - name: "proxy"
    docker_container: 
      name: bridge_proxy
      image: milvusdb/milvus:v2.0.1
      command: "milvus run proxy"
      env:
        ETCD_ENDPOINTS: "10.170.0.8:2379"
        MINIO_ADDRESS: "10.170.0.8:9000"
        PULSAR_ADDRESS: "pulsar://10.170.0.8:6650"
      network_mode: bridge
      ports:
        - "19530"
        - "9091" 
