---
- name: milvus-minio
  docker_container: 
    name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    env:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: "minio server /minio_data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: "{{ network }}"
    networks:
      - name: "{{ network }}"
        ipv4_address: "10.0.2.10"
    ports:
      - 9000